# Generated by Django 5.2 on 2025-04-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produto', '0002_remove_produto_detalhes_alter_produto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
